[env:tough]
platform = espressif32@6.9.0
board = m5stack-core2
framework = arduino
platform_packages =
    tool-esptoolpy @ file:///Users/coltonkirsten/.platformio/tools/tool-esptoolpy

upload_speed = 460800
monitor_speed = 115200
upload_port = /dev/cu.usbserial-53190105011
monitor_port = /dev/cu.usbserial-53190105011

monitor_filters = esp32_exception_decoder, time

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM

lib_deps =
    m5stack/M5Unified@0.2.19
    https://github.com/pschatzmann/ESP32-A2DP.git#v1.7.4
    fastled/FastLED@^3.7.8
